package com.example.booked.models;

/**
 * Report is generated by users to notify admins of inappropriate posts
 */
public class Report {

    //Properties
    private String description;
    private int category;
    private User owner;

    //Constructors
    //for firebase
    public Report() {
    }

    /**Constructor to initialize description, category and owner.
     * @param description
     * @param category
     * @param owner
     * */
    public Report(String description, int category, User owner) {
        this.description = description;
        this.category = category;
        this.owner = owner;
    }

    //Methods
    // accessor methods
    public int getCategory() {
        return category;
    }

    public String getDescription() {
        return description;
    }

    public User getOwner() {
        return owner;
    }

    //mutator methods
    public void setDescription(String description) {
        this.description = description;
    }

    public void setCategory(int category) {
        this.category = category;
    }

    public void setOwner(User owner) {
        this.owner = owner;
    }



}

